#!/usr/bin/env python3
"""Generate one work-history detail page per company: docs/work/<slug>.html.

docs/index.html shows the work history as a flow chart only -- company, role
and dates, each step a link. Everything the chart leaves out (the day-to-day
responsibilities, the nested project write-ups, the tools) lives here, one page
per company @subsection, so the CV stays scannable without losing the record.

    python3 tool/build_work_pages.py

The .dox stays the single source of truth -- this script only renders it. It
owns nothing but the files carrying GENERATED_MARK, so a hand-written file
dropped into docs/work/ is left alone and a company removed from the .dox has
its page deleted on the next run.
"""

import sys
from pathlib import Path

import cv_dox as C
import cv_html as H

REPO_ROOT = Path(__file__).resolve().parent.parent
DOX_FILE = REPO_ROOT / 'docs' / 'NguyenQuangBinh_CV.dox'
WORK_DIR = REPO_ROOT / 'docs' / 'work'

# Written into every page this script produces; the only thing it will delete.
GENERATED_MARK = '<!-- generated by tool/build_work_pages.py -->'

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{TITLE}} - {{NAME}} CV</title>
	<meta name="description" content="{{TITLE}} - role detail from the CV of {{NAME}}">

	<link rel="shortcut icon" href="../favicon.ico">

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">

	<!-- FontAwesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/bootstrap.min.css">

	<!-- Theme CSS -->
	<link rel="stylesheet" href="../assets/css/devresume.css">
	<link rel="stylesheet" href="../assets/css/work-flow.css">
</head>

<body>
	<div class="main-wrapper">
		<div class="container px-3 px-lg-5">
			<article class="resume-wrapper mx-auto theme-bg-light p-5 mb-5 my-5 shadow-lg">

				<nav class="work-page-nav" aria-label="Work history">
					<a class="resume-link" href="../index.html"><i class="fas fa-arrow-left mr-2"
							aria-hidden="true"></i>Back to CV</a>
					<ul class="work-page-links">
{{NAV}}
					</ul>
				</nav>

				<header class="work-page-header">
					<h1 class="work-page-company">{{TITLE}}</h1>
{{LOCATION}}
				</header>

				<div class="work-page-roles">
{{BODY}}
				</div>

				<p class="work-page-footer">
					<a class="resume-link" href="../index.html"><i class="fas fa-arrow-left mr-2"
							aria-hidden="true"></i>Back to CV</a>
				</p>

			</article>
		</div>
	</div>
	<!-- generated by tool/build_work_pages.py -->
</body>

</html>
"""


def render_nav(companies, current_key: str) -> str:
    """Chip links to every company page, the current one marked."""
    lines = []
    for company in companies:
        label, _ = H.split_title_dates(company.title)
        active = company.key == current_key
        cls = 'work-page-link is-active' if active else 'work-page-link'
        aria = ' aria-current="page"' if active else ''
        lines.append(
            f'\t\t\t\t\t\t<li><a class="{cls}" href="{H.work_slug(company.key)}.html"{aria}>'
            f'{H.inline_html(label)}</a></li>')
    return '\n'.join(lines)


def render_page(name: str, company: C.Block, companies: list) -> str:
    """One company's detail page: header, breadcrumb nav and the role bodies."""
    company_name, location = H.split_title_dates(company.title)
    location_html = ''
    if location:
        location_html = ('\t\t\t\t\t<p class="work-page-location">'
                         '<i class="fas fa-map-marker-alt mr-2" aria-hidden="true"></i>'
                         f'{H.inline_html(location)}</p>')

    page = PAGE_TEMPLATE
    for token, value in (
        ('{{NAME}}', H.inline_html(name)),
        ('{{TITLE}}', H.inline_html(company_name)),
        ('{{NAV}}', render_nav(companies, company.key)),
        ('{{LOCATION}}', location_html),
        ('{{BODY}}', H.render_company_roles(company)),
    ):
        page = page.replace(token, value)

    leftover = [t for t in ('{{NAME}}', '{{TITLE}}', '{{NAV}}', '{{LOCATION}}', '{{BODY}}')
                if t in page]
    if leftover:
        raise ValueError(f'unsubstituted template tokens: {leftover}')
    return page


def planned_pages(dox_text: str):
    """Return (name, {filename: html}) for the current .dox, or raise on trouble."""
    sections = C.parse_doc(dox_text)
    work = sections.get('work_experience')
    if work is None:
        raise ValueError('the .dox has no work_experience section')

    companies = H.work_companies(work)
    name = C.extract_name(dox_text)

    pages = {}
    seen = {}
    for company in companies:
        slug = H.work_slug(company.key)
        if slug in seen:
            raise ValueError(f'companies {seen[slug]!r} and {company.key!r} '
                             f'both map to work/{slug}.html')
        seen[slug] = company.key
        pages[f'{slug}.html'] = render_page(name, company, companies)
    return name, pages


def display(path: Path) -> str:
    """Repo-relative path for logs, falling back to the absolute one."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    if not DOX_FILE.exists():
        print(f'DOX file not found: {DOX_FILE}', file=sys.stderr)
        return 1

    try:
        _, pages = planned_pages(DOX_FILE.read_text(encoding='utf-8'))
    except ValueError as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        return 1

    WORK_DIR.mkdir(parents=True, exist_ok=True)

    for filename, page in pages.items():
        (WORK_DIR / filename).write_text(page, encoding='utf-8')
        print(f'wrote {display(WORK_DIR / filename)}')

    removed = []
    for path in sorted(WORK_DIR.glob('*.html')):
        if path.name in pages:
            continue
        if GENERATED_MARK in path.read_text(encoding='utf-8'):
            path.unlink()
            removed.append(path.name)
    if removed:
        print(f'removed stale page(s): {", ".join(removed)}')

    print(f'{len(pages)} work page(s) generated from {DOX_FILE.name}.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
